apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hql7ga8qt-go
  janus-idp.io/tekton: hql7ga8qt-go
  backstage.io/kubernetes-id: hql7ga8qt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hql7ga8qt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
