apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hql7ga8qt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hql7ga8qt-go 
  name: hql7ga8qt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hql7ga8qt-go 
